blank_issues_enabled: false
contact_links:
- name: Home Assistant Community
  url: https://community.home-assistant.io/
  about: Ask questions and discuss ideas with the Home Assistant community
- name: Documentation
  url: https://github.com/nijel/hass-cap-alerts/blob/main/README.md
  about: Read the integration documentation
